name: Publish Latest

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

env:
  REGISTRY: mario-pz/nvim
  USERNAME: ${{ github.actor }}
  PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: Build the Docker image
        run: |
            docker build . -t ${{ env.REGISTRY }}/${{ github.event.repository.name }}:latest

      - name: Push the Docker image
        run: |
            docker push ${{ env.REGISTRY }}/${{ github.event.repository.name }}:latest
