name: Publish Tag

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build . -t ghcr.io/${{ github.repository }}:${GITHUB_REF##*/}

      - name: Push the Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${GITHUB_REF##*/}
